services:
  todolist-app:
    container_name: todolist-app
    build: .
    image: todolist-app:0.0.0
    ports:
    - "3000:3000"
    env_file: .env
    networks:
      - todolist-network
  sonarqube:
    image: sonarqube:26.1.0.118079-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      
    networks:
      - todolist-network
    depends_on:
       - pg-todolist

  pg-todolist:
    image: postgres:15
    container_name: pg-todolist

    environment:
      POSTGRES_USER: postgresST
      POSTGRES_PASSWORD: postgresST
      POSTGRES_DB: todolistST
      TZ: "Atlantic/Cape_Verde"
    ports:
      - "5432:5432"
    networks:
      - todolist-network

    volumes:
      - pg15_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4:9.2
    container_name: pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 5050:80
    restart: unless-stopped
    volumes:
      - pgadmin-2025:/var/lib/pgadmin
    networks:
      - todolist-network
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    user: zap
    command: zap-webswing.sh
    ports:
      - "8080:8080"
      - "8090:8090"
    networks:
      - todolist-network
    volumes:
      - ./zap-data:/zap/wrk
    stdin_open: true
    tty: true



# Volume Persistente
volumes:
  pg15_data:
    name: pg15_data
  pgadmin-2025:
    name: pgadmin-2025
  sonarqube_data:
    name: sonarqube_data

networks:
  todolist-network:
    name: todolist-network
    external: true